#!/bin/bash

xt1="Instalando Swift..."
xt2="Verificando Dependencias"
xt3="Descargando Swift..."
xt4="Importando Claves PGP"
xt5="Actualizando Claves claves PGP"
xt6="Verificando Firma"
xt7="Descomprimiendo Swift..."
xt8="Instalando Swift..."
xt9="Agregando al Path"
xt10="Verificar Instalación, ejecuta:"
xt11="está instalado"
xt12="Arquitectura desconocida:"
url="https://www.swift.org/download/index.html"
varAmd(){ 
    a='s/.*\(https:\/\/[^ ]*\.tar\.gz\).*/\1/p'
    f='s/.*\(https:\/\/[^ ]*\.tar\.gz\.sig\).*/\1/p'
}
varArm(){
    a='s/.*\(https:\/\/[^ ]*aarch64\.tar\.gz\).*/\1/p'
    f='s/.*\(https:\/\/[^ ]*aarch64\.tar\.gz\.sig\).*/\1/p'
}

e(){
    echo -e "\e[1;${1}m${2}\e[0m"
}

D(){
    curl -s $url | sed -n "$1" | uniq | head -n 1 | xargs curl -O -J -L
}

check() {
    for name in "$@"; do
        dpkg -s "$name" >/dev/null 2>&1
        if [ $? -eq 0 ]; then
            e 96 "$name $xt11"
        else
            e 96 $xt1
            apt install "$name" -y
        fi
    done
}

iSwift(){
e 96 "$xt1"
e 96 "$xt2"

check "libtinfo5" "libncurses5" "libncurses6" "zlib1g-dev" "htop" "gnupg" "curl"

rm -rf /usr/local/swift
sed -i '/export PATH=\/usr\/local\/swift\/usr\/bin:"${PATH}"/d' ~/.bashrc
sed -i '/export LD_LIBRARY_PATH=\/usr\/local\/swift\/usr\/lib\/swift\/linux:"${LD_LIBRARY_PATH}"/d' ~/.bashrc

cd /usr/local
e 96 "$xt3"

D "$a"
D "$f"

e 96 "$xt4"

gpg --keyserver hkp://keyserver.ubuntu.com \
      --recv-keys \
      '7463 A81A 4B2E EA1B 551F  FBCF D441 C977 412B 37AD' \
      '1BE1 E29A 084C B305 F397  D62A 9F59 7F4D 21A5 6D5F' \
      'A3BA FD35 56A5 9079 C068  94BD 63BC 1CFE 91D3 06C6' \
      '5E4D F843 FB06 5D7F 7E24  FBA2 EF54 30F0 71E1 B235' \
      '8513 444E 2DA3 6B7C 1659  AF4D 7638 F1FB 2B2B 08C4' \
      'A62A E125 BBBF BB96 A6E0  42EC 925C C1CC ED3D 1561' \
      '8A74 9566 2C3C D4AE 18D9  5637 FAF6 989E 1BC1 6FEA' \
      'E813 C892 820A 6FA1 3755  B268 F167 DF1A CF9C E069'

e 96 "$xt5"
gpg --keyserver hkp://keyserver.ubuntu.com --refresh-keys Swift
e 96 "$xt6"
gpg --verify swift*.sig

e 96 "$xt7"
tar xzf swift*.tar.gz

e 96 "$xt8"
mv swift*/ swift

e 96 "$xt9"
echo 'export PATH=/usr/local/swift/usr/bin:"${PATH}"' >> ~/.bashrc
echo 'export LD_LIBRARY_PATH=/usr/local/swift/usr/lib/swift/linux:"${LD_LIBRARY_PATH}"' >> ~/.bashrc

cd ~/
. ~/.bashrc
e 96 "$xt10"
echo ". ~/.bashrc;swift --version"
#end iSwift
}

archi=$(uname -m)
if [[ $archi == "x86_64" ]]; then
    varAmd
    iSwift
elif [[ $archi == "aarch64" ]]; then
    varArm
    iSwift
else
    echo "$xt12 $archi"
fi
